language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer install
  - composer dump-autoload -o

script: vendor/bin/phpunit

notifications:
  email:
    - dbyoung2@gmail.com

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true