language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script: vendor/bin/phpunit --verbose

notifications:
  email:
    - dave@opulencephp.com

sudo: false

matrix:
  allow_failures:
    - php: 7.1
  fast_finish: true