language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer install
  - composer dump-autoload -o
  - echo 'date.timezone = "UTC"' > travis.php.ini
  - echo 'timezone = "UTC"' > travis.hhvm.ini
  - hhvm -c travis.hhvm.ini
  - phpenv config-add travis.php.ini

script: vendor/bin/phpunit --verbose

notifications:
  email:
    - dbyoung2@gmail.com

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true