language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer install
  - composer dump-autoload -o
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: vendor/bin/phpunit --verbose

notifications:
  email:
    - dbyoung2@gmail.com

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true